name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    environment:
      name: https://lakar.glitch.me
    env:
      GLITCH_REPO: ${{secrets.GLITCH_REPO}}
    runs-on: ubuntu-latest
    steps:
      - run: "git clone https://github.com/davidsdevel/lakar-call /root/source --origin source"
      - run: cd /root/source

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: /root/source/.next/cache
          key: lettercms-${{github.ref_name}}-lakar-${{hashFiles('yarn.lock')}}
          restore-keys: |
            lettercms-${{github.ref_name}}-lakar-
            lettercms-${{github.ref_name}}-
            lettercms-

      - run: yarn
      - run: yarn build
      - run: rm .gitignore
      - run: echo .next/cache >> .gitignore
      - run: echo node_modules >> .gitignore
      - run: git remote add glitch "$GLITCH_REPO"
      - run: git add .
      - run: git commit -m "Deploy"
      - run: git push glitch master


