name: Deploy to Glitch

on:
  push:
    branches:
      - main

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  deploy-signaling:
    runs-on: ubuntu-latest
    env:
        REPO_SOURCE: ${{ secrets.GLITCH_REPO }}
        GLITCH_SECRET: ${{ secrets.GLITCH_SECRET }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - run: npx glitch-deploy-tool from-local -p ./apps/signaling -r $REPO_SOURCE -v
      - run: 'curl -X POST https://lakar.glitch.me/git -H "content-type: application/json" -d "{\"secret\": \"$GLITCH_SECRET\"}"'
