name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    environment:
      name: https://lakar.glitch.me
    env:
      GLITCH_REPO: ${{secrets.GLITCH_REPO}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

     - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./.next/cache
          key: lettercms-${{github.ref_name}}-lakar-${{hashFiles('yarn.lock')}}
          restore-keys: |
            lettercms-${{github.ref_name}}-lakar-
            lettercms-${{github.ref_name}}-
            lettercms-

      - name: Build
        run: yarn build
      - run: rm .gitignore
      - run: echo .next/cache >> .gitignore
      - run: echo node_modules >> .gitignore
      - run: git remote add glitch "$GLITCH_REPO"
      - run: git commit -m "Deploy"
      - run: git push destination master


